language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "graceshopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: bookshoper1
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: ewAQ7sp/qk5khjywBliPadLR9dQweZgfzfhKQtsWIhOetz2+oKrTaazEid/o160EfgzyYbWgZGgN9weAbxXWP0nt8FDC8YNLec0eAtpaEpwqT7AEb8OObA/jhsaoWo6Yj4biUWWsjWSCLLQV+yJ2W/kz+RmT5qRH57AVH5mIsZ1iWresXgnZ6nbJlYcioP2wpht/7CXI3xztQIkYAJnS7APRGo4M2OJhl4OmlKGnzQPcChXjwERTzW9VJAwMy10aOLM5c2oC0fR8oIsklzGpo4nqmqYkYWlBw0op7OqXBTFG3JRuFDZKx3OCI0e5JTCuUpHC6gfP5buATwSbypQnqGtCVSK33q4B3AJKbssASXadX+V6U5xcyAdLLQn4bXGEUepYi9gOG8f6UmmN03xcyBiXZwdUgArTjnnePX2pkj3X58cUVe3sR39CnM2ZGcEdVXTz2mUU274RhX4d1za5kgzVx6a1W+psgljM82VYOTpc6UixnULWBju9yPLcSc+/A9MGWoo5rIhdFTr4Pi+/y9Sm/8okLRVYek1VNmjQWfNT35/Ee1Jey+b7YsoBSn0Er2ppDbCACAKO3jQn75IOt8pClSFlQKk5X/WxfjlPfOCbitDGip7Da5d0FrKMzpwykmWkcrBzR5TtXJsZHZBMEP5hu4xxztkMdsv2KhW0ogs=
